# -*- coding: utf-8 -*-
"""Fundamental Of Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhftzYmhE0W1OJzpaiJSCXGweMrgb6d8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('data9_1568485286.xlsx',header=None,names=['Weights'])

df

df['Weights'].describe()

weights = df['Weights']

bins = np.arange(1.9, 4.8, 0.1)
hist, bins = np.histogram(weights, bins=bins, density=True)
bin_centers = (bins[:-1] + bins[1:]) / 2

W = np.average(bin_centers, weights=hist)

X = bins[np.argmax(np.cumsum(hist * np.diff(bins)) >= 0.1)]

fig, ax = plt.subplots()
ax.bar(bin_centers, hist, width=0.1, alpha=0.5, label='Newborn weights')
ax.axvline(x=W, color='red', linestyle='--', label='Average weight')
ax.axvline(x=X, color='black', linestyle='--', label='10% threshold')

ax.set_xlabel('Weights')
ax.set_ylabel('Density')
ax.set_title('Distribution of Newborn Weights')
ax.legend()

ax.text(0.05, 0.95, 'Average weight: {:.2f}'.format(W),
        transform=ax.transAxes, ha='left', va='top')
ax.text(0.05, 0.85, 'Weight value X: {:.2f}'.format(X),
        transform=ax.transAxes, ha='left', va='top')

plt.show()

